name: Cloudflare
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: nathanvaughn/actions-cloudflare-purge@master
      with:
        cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
        cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}